### ISSUE TITLE
[Bug]: AOT 10: typo

### ISSUE THREAD

**Issue by y1hao** [typehero/typehero#1299]
### What happened?

The placeholder solution has a typo:
```ts
type StreetSufixTester = unknown;
```

Should be:
```diff
- type StreetSufixTester = unknown;
+ type StreetSuffixTester = unknown;
```

**Comment by the-dijkstra** [comment]
Can confirm.

**Comment by Sachin-chaurasiya** [comment]
Hello @the-dijkstra , I would like to work on this.

**Comment by the-dijkstra** [comment]
Hey @Sachin-chaurasiya I'm not a maintainer. but I'm sure the maintainers of this repo would welcome your contributions.

**Comment by bautistaaa** [comment]
fixed already :)

thanks for making an issue though ❤️❤️

**Comment by y1hao** [comment]
@bautistaaa Thanks for the fix. Just curious, since I did not find where the challenges of AOT are defined by searching the code base, I'm guessing they are secretly injected into the database via the admin portal. Is this the case?

**Comment by bautistaaa** [comment]
i have access to the prod db so i can do whatever basically

**Comment by Eroxl** [comment]
> fixed already :)
> 
> thanks for making an issue though ❤️❤️

Just did the challenge today it's still showing the typo, might wanna take another look
https://typehero.dev/challenge/day-10

**Comment by bautistaaa** [comment]
messed up my script will fix later
